### ISSUE TITLE
The matching logic doesn't support the extension of HTTP Requests

### ISSUE THREAD

**Issue by davegogol** [davegogol/mock-microservice#1]
If I have an HTTP Request (A) which extends an other one (B), for instance with additional headers/parameters, and in the database I've set up both, it'll return B if defined sooner than A in httpRequestResponsePairs.json. 
Even if I don't setup A, it'll return B. This happens because each item in the database is compared to the incoming request, if all the fields in the database item match, it'll suddenly return the respective response, ignoring if better matching are defined later in the database. A solution might be to gather all the matching requests, giving back the one with more "weight" (based on the matching).

An example, follows... 

HTTP Request A:

``` json
{
  "route":  {"path": "/monitoring"},
  "method": "GET",
  "headers" : { "authentication" : "basic 12345678" }
  }
}
```

HTTP Request B:

``` json
{
  "route":  {"path": "/monitoring"},
  "method": "GET"
  }
}
```

httpRequestResponsePairs.json configuration: 

``` json
{
  "GET-MOCK" :
  {
    "request": {
      "endpoint": "/monitoring",
      "method": "GET"
    },
    "response": {
      "content": "Alive",
      "code": "200"
    }
  },
  "GET-MOCK-WITH-HEADERS" : {
    "request": {
      "endpoint": "/monitoring",
      "method": "GET",
      "headers": { "authentication" : "basic 12345678" }
    },
    "response": {
      "content": "Alive (extension)",
      "code": "200"
    }
  }
}
```

It'll always return "GET-MOCK"  response, because it's defined before.

**Comment by zsolt-kali** [comment]
Compare everything with deep equal (should have the same) but the headers.
